# Indian meal dataset for diet recommendation app
# Tuple format: (meal_name, calories, protein, region, budget, prep_time, diet_type, meal_category)

# Total meals: 661

meals = [
    ("Warm Lemon Water", 10, 0, "all", "low", "quick", "veg", "snack"),
    ("Green Tea", 5, 0, "all", "low", "quick", "veg", "snack"),
    ("Black Coffee", 5, 0, "all", "low", "quick", "veg", "snack"),
    ("Protein Shake", 180, 25, "all", "medium", "quick", "veg", "snack"),
    ("Fruit Bowl", 120, 2, "all", "low", "quick", "veg", "snack"),
    ('Poha', 250, 6, 'north', 'low', 'quick', 'veg', 'breakfast'),
    ('Bread Upma', 220, 7, 'north', 'low', 'quick', 'veg', 'breakfast'),
    ('Banana Shake', 300, 10, 'north', 'low', 'quick', 'veg', 'breakfast'),
    ('Dal Tadka', 350, 18, 'north', 'low', 'quick', 'veg', 'lunch'),
    ('Rajma Chawal', 450, 20, 'north', 'low', 'medium', 'veg', 'lunch'),
    ('Chole Bhature', 500, 16, 'north', 'low', 'medium', 'veg', 'lunch'),
    ('Paneer Bhurji', 300, 20, 'north', 'low', 'quick', 'veg', 'dinner'),
    ('Aloo Paratha', 350, 8, 'north', 'low', 'medium', 'veg', 'breakfast'),
    ('Moong Dal Chilla', 200, 14, 'north', 'low', 'quick', 'veg', 'breakfast'),
    ('Palak Paneer', 320, 18, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Egg Bhurji', 250, 18, 'north', 'low', 'quick', 'nonveg', 'breakfast'),
    ('Boiled Eggs + Toast', 280, 20, 'north', 'low', 'quick', 'nonveg', 'breakfast'),
    ('Chicken Curry + Rice', 520, 38, 'north', 'low', 'medium', 'nonveg', 'lunch'),
    ('Egg Fried Rice', 400, 18, 'north', 'low', 'quick', 'nonveg', 'lunch'),
    ('Chicken Keema', 430, 35, 'north', 'low', 'medium', 'nonveg', 'dinner'),
    ('Omelette Roll', 300, 20, 'north', 'low', 'quick', 'nonveg', 'breakfast'),
    ('Chicken Soup', 180, 22, 'north', 'low', 'quick', 'nonveg', 'dinner'),
    ('Mutton Curry + Roti', 550, 40, 'north', 'medium', 'long', 'nonveg', 'dinner'),
    ('Idli Sambar', 250, 10, 'south', 'low', 'quick', 'veg', 'breakfast'),
    ('Masala Dosa', 320, 8, 'south', 'low', 'medium', 'veg', 'breakfast'),
    ('Upma', 220, 7, 'south', 'low', 'quick', 'veg', 'breakfast'),
    ('Rasam Rice', 300, 8, 'south', 'low', 'quick', 'veg', 'lunch'),
    ('Sambar Rice', 380, 14, 'south', 'low', 'medium', 'veg', 'lunch'),
    ('Pongal', 350, 10, 'south', 'low', 'medium', 'veg', 'breakfast'),
    ('Coconut Chutney Sandwich', 200, 6, 'south', 'low', 'quick', 'veg', 'snack'),
    ('Vegetable Uttapam', 280, 9, 'south', 'low', 'medium', 'veg', 'breakfast'),
    ('Fish Curry + Rice', 480, 35, 'south', 'low', 'medium', 'nonveg', 'lunch'),
    ('Prawn Masala + Rice', 500, 32, 'south', 'medium', 'medium', 'nonveg', 'dinner'),
    ('Egg Dosa', 310, 16, 'south', 'low', 'quick', 'nonveg', 'breakfast'),
    ('Chicken Chettinad', 520, 40, 'south', 'medium', 'long', 'nonveg', 'dinner'),
    ('Oats Smoothie', 250, 10, 'all', 'low', 'quick', 'veg', 'breakfast'),
    ('Banana + Peanut Butter', 320, 12, 'all', 'low', 'quick', 'veg', 'snack'),
    ('Sprouts Salad', 180, 14, 'all', 'low', 'quick', 'veg', 'snack'),
    ('Curd Rice', 280, 9, 'all', 'low', 'quick', 'veg', 'lunch'),
    ('Sattu Drink', 200, 12, 'all', 'low', 'quick', 'veg', 'breakfast'),
    ('Chana Chaat', 220, 10, 'all', 'low', 'quick', 'veg', 'snack'),
    ('Whey + Banana Shake', 350, 28, 'all', 'medium', 'quick', 'nonveg', 'breakfast'),
    ('Greek Yogurt + Nuts', 300, 18, 'all', 'medium', 'quick', 'veg', 'snack'),
    ('Tofu Stir Fry', 310, 22, 'all', 'medium', 'quick', 'veg', 'dinner'),
    ('Paneer Salad', 270, 20, 'all', 'medium', 'quick', 'veg', 'snack'),
    ('Paneer Butter Masala', 450, 20, 'north', 'high', 'medium', 'veg', 'dinner'),
    ('Dal Makhani', 400, 18, 'north', 'high', 'long', 'veg', 'lunch'),
    ('Chicken Biryani', 600, 35, 'north', 'high', 'long', 'nonveg', 'lunch'),
    ('Grilled Chicken Breast', 350, 40, 'all', 'high', 'medium', 'nonveg', 'dinner'),
    ('Ghee Roast Dosa', 420, 10, 'south', 'high', 'medium', 'veg', 'breakfast'),
    ('Fish Fry', 450, 35, 'south', 'high', 'medium', 'nonveg', 'dinner'),
    ('Almond Smoothie', 300, 12, 'all', 'high', 'quick', 'veg', 'snack'),
    ('Protein Shake Plant', 280, 25, 'all', 'high', 'quick', 'veg', 'snack'),
    ('Chole Kulche', 420, 15, 'north', 'low', 'medium', 'veg', 'dinner'),
    ('Amritsari Kulcha', 320, 10, 'north', 'low', 'quick', 'veg', 'breakfast'),
    ('Sarson Ka Saag + Makki Roti', 420, 15, 'north', 'low', 'medium', 'veg', 'dinner'),
    ('Paneer Paratha', 320, 18, 'north', 'low', 'quick', 'veg', 'breakfast'),
    ('Gobhi Paratha', 320, 10, 'north', 'low', 'quick', 'veg', 'breakfast'),
    ('Methi Paratha', 320, 10, 'north', 'low', 'quick', 'veg', 'breakfast'),
    ('Sattu Paratha', 320, 18, 'north', 'low', 'quick', 'veg', 'breakfast'),
    ('Kadhi Chawal', 420, 15, 'north', 'low', 'medium', 'veg', 'lunch'),
    ('Kadhi + Roti', 420, 15, 'north', 'low', 'medium', 'veg', 'dinner'),
    ('Mix Veg + Roti', 420, 15, 'north', 'low', 'medium', 'veg', 'dinner'),
    ('Bhindi Masala + Roti', 420, 15, 'north', 'low', 'medium', 'veg', 'dinner'),
    ('Baingan Bharta + Roti', 420, 15, 'north', 'low', 'medium', 'veg', 'dinner'),
    ('Aloo Gobi + Roti', 420, 15, 'north', 'low', 'medium', 'veg', 'dinner'),
    ('Jeera Rice + Dal', 420, 23, 'north', 'low', 'medium', 'veg', 'lunch'),
    ('Rajma + Roti', 420, 23, 'north', 'low', 'medium', 'veg', 'dinner'),
    ('Chole + Roti', 420, 15, 'north', 'low', 'medium', 'veg', 'dinner'),
    ('Chole Chawal', 420, 15, 'north', 'low', 'medium', 'veg', 'lunch'),
    ('Dal Fry + Roti', 420, 23, 'north', 'low', 'medium', 'veg', 'dinner'),
    ('Dal Palak + Roti', 420, 23, 'north', 'low', 'medium', 'veg', 'dinner'),
    ('Aloo Matar + Roti', 420, 15, 'north', 'low', 'medium', 'veg', 'dinner'),
    ('Matar Paneer + Roti', 420, 23, 'north', 'low', 'medium', 'veg', 'dinner'),
    ('Paneer Tikka', 420, 23, 'north', 'low', 'medium', 'veg', 'dinner'),
    ('Paneer Tikka + Roti', 420, 23, 'north', 'low', 'medium', 'veg', 'dinner'),
    ('Malai Kofta + Roti', 500, 15, 'north', 'high', 'medium', 'veg', 'dinner'),
    ('Shahi Paneer + Roti', 500, 23, 'north', 'high', 'medium', 'veg', 'dinner'),
    ('Tandoori Roti + Dal', 420, 23, 'north', 'low', 'medium', 'veg', 'dinner'),
    ('Missi Roti + Curd', 420, 15, 'north', 'low', 'medium', 'veg', 'dinner'),
    ('Dahi Bhalla', 420, 15, 'north', 'low', 'medium', 'veg', 'dinner'),
    ('Papdi Chaat', 240, 9, 'north', 'low', 'quick', 'veg', 'snack'),
    ('Aloo Tikki', 420, 15, 'north', 'low', 'medium', 'veg', 'dinner'),
    ('Bread Pakora', 240, 9, 'north', 'low', 'quick', 'veg', 'snack'),
    ('Samosa Chole', 240, 9, 'north', 'low', 'quick', 'veg', 'snack'),
    ('Matar Kulcha', 320, 10, 'north', 'low', 'quick', 'veg', 'breakfast'),
    ('Veg Pulao', 420, 15, 'north', 'low', 'medium', 'veg', 'dinner'),
    ('Tehri', 420, 15, 'north', 'low', 'medium', 'veg', 'dinner'),
    ('Dum Aloo + Roti', 420, 15, 'north', 'low', 'medium', 'veg', 'dinner'),
    ('Lauki Kofta + Roti', 420, 15, 'north', 'low', 'medium', 'veg', 'dinner'),
    ('Karela Sabzi + Roti', 420, 15, 'north', 'low', 'medium', 'veg', 'dinner'),
    ('Tinda Sabzi + Roti', 420, 15, 'north', 'low', 'medium', 'veg', 'dinner'),
    ('Mooli Paratha', 320, 10, 'north', 'low', 'quick', 'veg', 'breakfast'),
    ('Besan Chilla', 320, 10, 'north', 'low', 'quick', 'veg', 'breakfast'),
    ('Suji Cheela', 320, 10, 'north', 'low', 'quick', 'veg', 'breakfast'),
    ('Veg Stuffed Sandwich', 240, 9, 'north', 'low', 'quick', 'veg', 'snack'),
    ('Makki Roti + Sarson Saag', 420, 15, 'punjab', 'low', 'medium', 'veg', 'dinner'),
    ('Punjabi Chole + Rice', 420, 15, 'punjab', 'low', 'medium', 'veg', 'lunch'),
    ('Amritsari Chole + Kulcha', 320, 10, 'punjab', 'low', 'quick', 'veg', 'breakfast'),
    ('Paneer Lababdar + Roti', 420, 23, 'punjab', 'low', 'medium', 'veg', 'dinner'),
    ('Paneer Makhani + Naan', 500, 23, 'punjab', 'high', 'medium', 'veg', 'dinner'),
    ('Punjabi Kadhi Pakora + Rice', 240, 9, 'punjab', 'low', 'quick', 'veg', 'snack'),
    ('Rajma Masala + Rice', 420, 23, 'punjab', 'low', 'medium', 'veg', 'lunch'),
    ('Lassi + Paratha', 320, 10, 'punjab', 'low', 'quick', 'veg', 'breakfast'),
    ('Aloo Kulcha + Curd', 320, 10, 'punjab', 'low', 'quick', 'veg', 'breakfast'),
    ('Dal Makhani + Naan', 500, 23, 'punjab', 'high', 'medium', 'veg', 'dinner'),
    ('Tandoori Paneer Wrap', 240, 17, 'punjab', 'low', 'quick', 'veg', 'snack'),
    ('Punjabi Samosa Chaat', 240, 9, 'punjab', 'low', 'quick', 'veg', 'snack'),
    ('Butter Chicken + Roti', 520, 36, 'punjab', 'medium', 'medium', 'nonveg', 'dinner'),
    ('Chicken Tikka', 360, 30, 'punjab', 'medium', 'medium', 'nonveg', 'dinner'),
    ('Tandoori Chicken', 360, 30, 'punjab', 'medium', 'medium', 'nonveg', 'dinner'),
    ('Chicken Seekh Kebab', 360, 30, 'punjab', 'medium', 'medium', 'nonveg', 'dinner'),
    ('Chicken Curry + Roti', 520, 36, 'punjab', 'medium', 'medium', 'nonveg', 'dinner'),
    ('Egg Curry + Roti', 520, 36, 'punjab', 'medium', 'medium', 'nonveg', 'dinner'),
    ('Keema Paratha', 360, 30, 'punjab', 'medium', 'medium', 'nonveg', 'breakfast'),
    ('Mutton Curry + Naan', 360, 30, 'punjab', 'high', 'long', 'nonveg', 'dinner'),
    ('Amritsari Fish Fry', 360, 30, 'punjab', 'medium', 'medium', 'nonveg', 'dinner'),
    ('Chicken Pakora', 360, 30, 'punjab', 'medium', 'medium', 'nonveg', 'snack'),
    ('Plain Dosa', 320, 10, 'south', 'low', 'quick', 'veg', 'breakfast'),
    ('Rava Dosa', 320, 10, 'south', 'low', 'quick', 'veg', 'breakfast'),
    ('Mysore Masala Dosa', 320, 10, 'south', 'low', 'quick', 'veg', 'breakfast'),
    ('Onion Dosa', 320, 10, 'south', 'low', 'quick', 'veg', 'breakfast'),
    ('Set Dosa', 320, 10, 'south', 'low', 'quick', 'veg', 'breakfast'),
    ('Neer Dosa', 320, 10, 'south', 'low', 'quick', 'veg', 'breakfast'),
    ('Pesarattu', 320, 10, 'south', 'low', 'quick', 'veg', 'breakfast'),
    ('Adai Dosa', 320, 10, 'south', 'low', 'quick', 'veg', 'breakfast'),
    ('Medu Vada', 240, 9, 'south', 'low', 'quick', 'veg', 'snack'),
    ('Idli Vada Combo', 240, 9, 'south', 'low', 'quick', 'veg', 'snack'),
    ('Ragi Idli', 320, 10, 'south', 'low', 'quick', 'veg', 'breakfast'),
    ('Rava Idli', 320, 10, 'south', 'low', 'quick', 'veg', 'breakfast'),
    ('Kanchipuram Idli', 320, 10, 'south', 'low', 'quick', 'veg', 'breakfast'),
    ('Tomato Rice', 420, 15, 'south', 'low', 'medium', 'veg', 'lunch'),
    ('Lemon Rice', 420, 15, 'south', 'low', 'medium', 'veg', 'lunch'),
    ('Tamarind Rice', 420, 15, 'south', 'low', 'medium', 'veg', 'lunch'),
    ('Coconut Rice', 420, 15, 'south', 'low', 'medium', 'veg', 'lunch'),
    ('Bisi Bele Bath', 420, 15, 'south', 'low', 'medium', 'veg', 'dinner'),
    ('Avial + Rice', 420, 15, 'south', 'low', 'medium', 'veg', 'lunch'),
    ('Vegetable Kurma + Appam', 320, 10, 'south', 'low', 'quick', 'veg', 'breakfast'),
    ('Appam + Stew', 320, 10, 'south', 'low', 'quick', 'veg', 'breakfast'),
    ('Puttu + Kadala Curry', 320, 18, 'south', 'low', 'quick', 'veg', 'breakfast'),
    ('Kerala Parotta + Kurma', 420, 15, 'south', 'low', 'medium', 'veg', 'dinner'),
    ('Malabar Veg Biryani', 420, 15, 'south', 'low', 'medium', 'veg', 'lunch'),
    ('Vegetable Sagu + Poori', 420, 15, 'south', 'low', 'medium', 'veg', 'dinner'),
    ('Akki Roti', 420, 15, 'south', 'low', 'medium', 'veg', 'dinner'),
    ('Ragi Mudde + Sambar', 420, 15, 'south', 'low', 'medium', 'veg', 'dinner'),
    ('Pongal + Chutney', 240, 9, 'south', 'low', 'quick', 'veg', 'snack'),
    ('Curd Vada', 240, 9, 'south', 'low', 'quick', 'veg', 'snack'),
    ('Sambar Vada', 240, 9, 'south', 'low', 'quick', 'veg', 'snack'),
    ('Mini Idli Sambar', 320, 10, 'south', 'low', 'quick', 'veg', 'breakfast'),
    ('Uttapam + Chutney', 240, 9, 'south', 'low', 'quick', 'veg', 'snack'),
    ('Rasam + Rice', 420, 15, 'south', 'low', 'medium', 'veg', 'lunch'),
    ('Vangi Bath', 420, 15, 'south', 'low', 'medium', 'veg', 'dinner'),
    ('Puliyogare', 420, 15, 'south', 'low', 'medium', 'veg', 'dinner'),
    ('Kozhukattai', 420, 15, 'south', 'low', 'medium', 'veg', 'dinner'),
    ('Sundal', 420, 23, 'south', 'low', 'medium', 'veg', 'dinner'),
    ('Kothu Parotta Veg', 420, 15, 'south', 'low', 'medium', 'veg', 'dinner'),
    ('Ven Pongal', 320, 10, 'tamil_nadu', 'low', 'quick', 'veg', 'breakfast'),
    ('Kuzhi Paniyaram', 420, 15, 'tamil_nadu', 'low', 'medium', 'veg', 'dinner'),
    ('Idiyappam + Coconut Milk', 320, 10, 'tamil_nadu', 'low', 'quick', 'veg', 'breakfast'),
    ('Kothu Parotta Egg', 360, 30, 'tamil_nadu', 'medium', 'medium', 'nonveg', 'dinner'),
    ('Chicken 65', 360, 30, 'tamil_nadu', 'medium', 'medium', 'nonveg', 'dinner'),
    ('Chettinad Chicken + Rice', 520, 36, 'tamil_nadu', 'medium', 'medium', 'nonveg', 'lunch'),
    ('Meen Kuzhambu + Rice', 420, 15, 'tamil_nadu', 'low', 'medium', 'veg', 'lunch'),
    ('Paruppu Sadam', 420, 15, 'tamil_nadu', 'low', 'medium', 'veg', 'dinner'),
    ('Keerai Kootu + Rice', 420, 15, 'tamil_nadu', 'low', 'medium', 'veg', 'lunch'),
    ('Poriyal + Rasam Rice', 420, 15, 'tamil_nadu', 'low', 'medium', 'veg', 'lunch'),
    ('Curd Rice + Pickle', 420, 15, 'tamil_nadu', 'low', 'medium', 'veg', 'lunch'),
    ('Milagu Rasam', 420, 15, 'tamil_nadu', 'low', 'medium', 'veg', 'dinner'),
    ('Kara Kuzhambu + Rice', 420, 15, 'tamil_nadu', 'low', 'medium', 'veg', 'lunch'),
    ('Egg Kalakki', 360, 30, 'tamil_nadu', 'medium', 'medium', 'nonveg', 'dinner'),
    ('Mutton Chukka', 360, 30, 'tamil_nadu', 'high', 'long', 'nonveg', 'dinner'),
    ('Fish Fry + Rasam Rice', 520, 36, 'tamil_nadu', 'medium', 'medium', 'nonveg', 'lunch'),
    ('Appam + Egg Curry', 360, 30, 'kerala', 'medium', 'medium', 'nonveg', 'breakfast'),
    ('Appam + Kadala Curry', 320, 18, 'kerala', 'low', 'quick', 'veg', 'breakfast'),
    ('Puttu + Banana', 320, 10, 'kerala', 'low', 'quick', 'veg', 'breakfast'),
    ('Puttu + Egg Curry', 360, 30, 'kerala', 'medium', 'medium', 'nonveg', 'breakfast'),
    ('Kerala Sadya', 420, 15, 'kerala', 'low', 'medium', 'veg', 'dinner'),
    ('Olan + Rice', 420, 15, 'kerala', 'low', 'medium', 'veg', 'lunch'),
    ('Erissery + Rice', 420, 15, 'kerala', 'low', 'medium', 'veg', 'lunch'),
    ('Thoran + Rice', 420, 15, 'kerala', 'low', 'medium', 'veg', 'lunch'),
    ('Kerala Fish Curry + Rice', 520, 36, 'kerala', 'medium', 'medium', 'nonveg', 'lunch'),
    ('Karimeen Pollichathu', 420, 15, 'kerala', 'low', 'medium', 'veg', 'dinner'),
    ('Malabar Chicken Biryani', 520, 36, 'kerala', 'medium', 'medium', 'nonveg', 'lunch'),
    ('Beef Ularthiyathu', 360, 30, 'kerala', 'high', 'long', 'nonveg', 'dinner'),
    ('Chicken Stew + Appam', 360, 30, 'kerala', 'medium', 'medium', 'nonveg', 'breakfast'),
    ('Prawn Roast + Rice', 520, 36, 'kerala', 'high', 'long', 'nonveg', 'lunch'),
    ('Kappa + Fish Curry', 360, 30, 'kerala', 'medium', 'medium', 'nonveg', 'dinner'),
    ('Ada Pradhaman', 260, 6, 'kerala', 'medium', 'medium', 'veg', 'dessert'),
    ('Palada Payasam', 260, 6, 'kerala', 'medium', 'medium', 'veg', 'dessert'),
    ('Andhra Pesarattu', 320, 10, 'andhra', 'low', 'quick', 'veg', 'breakfast'),
    ('Andhra Meals', 420, 15, 'andhra', 'low', 'medium', 'veg', 'dinner'),
    ('Gongura Rice', 420, 15, 'andhra', 'low', 'medium', 'veg', 'lunch'),
    ('Pulihora', 420, 15, 'andhra', 'low', 'medium', 'veg', 'dinner'),
    ('Tomato Pappu + Rice', 420, 15, 'andhra', 'low', 'medium', 'veg', 'lunch'),
    ('Gutti Vankaya + Rice', 420, 15, 'andhra', 'low', 'medium', 'veg', 'lunch'),
    ('Andhra Chicken Curry + Rice', 520, 36, 'andhra', 'medium', 'medium', 'nonveg', 'lunch'),
    ('Kodi Pulusu', 360, 30, 'andhra', 'medium', 'medium', 'nonveg', 'dinner'),
    ('Royyala Iguru', 360, 30, 'andhra', 'medium', 'medium', 'nonveg', 'dinner'),
    ('Egg Pulusu + Rice', 520, 36, 'andhra', 'medium', 'medium', 'nonveg', 'lunch'),
    ('Ragi Sangati + Chicken Curry', 360, 30, 'andhra', 'medium', 'medium', 'nonveg', 'dinner'),
    ('Mirchi Bajji', 240, 9, 'andhra', 'low', 'quick', 'veg', 'snack'),
    ('Punugulu', 240, 9, 'andhra', 'low', 'quick', 'veg', 'snack'),
    ('Hyderabadi Veg Biryani', 420, 15, 'telangana', 'low', 'medium', 'veg', 'lunch'),
    ('Hyderabadi Chicken Biryani', 520, 36, 'telangana', 'medium', 'medium', 'nonveg', 'lunch'),
    ('Bagara Rice + Dalcha', 420, 23, 'telangana', 'low', 'medium', 'veg', 'lunch'),
    ('Sakinalu', 420, 15, 'telangana', 'low', 'medium', 'veg', 'dinner'),
    ('Sarva Pindi', 420, 15, 'telangana', 'low', 'medium', 'veg', 'dinner'),
    ('Jonna Roti + Curry', 420, 15, 'telangana', 'low', 'medium', 'veg', 'dinner'),
    ('Pachi Pulusu + Rice', 420, 15, 'telangana', 'low', 'medium', 'veg', 'lunch'),
    ('Mutton Dalcha + Rice', 520, 36, 'telangana', 'high', 'long', 'nonveg', 'lunch'),
    ('Egg Biryani', 520, 36, 'telangana', 'medium', 'medium', 'nonveg', 'lunch'),
    ('Kodi Kura + Rice', 520, 36, 'telangana', 'medium', 'medium', 'nonveg', 'lunch'),
    ('Double Ka Meetha', 260, 6, 'telangana', 'medium', 'medium', 'veg', 'dessert'),
    ('Qubani Ka Meetha', 260, 6, 'telangana', 'medium', 'medium', 'veg', 'dessert'),
    ('Vada Pav', 240, 9, 'maharashtra', 'low', 'quick', 'veg', 'snack'),
    ('Misal Pav', 320, 10, 'maharashtra', 'low', 'quick', 'veg', 'breakfast'),
    ('Pav Bhaji', 320, 10, 'maharashtra', 'low', 'quick', 'veg', 'breakfast'),
    ('Sabudana Khichdi', 420, 15, 'maharashtra', 'low', 'medium', 'veg', 'dinner'),
    ('Kanda Poha', 320, 10, 'maharashtra', 'low', 'quick', 'veg', 'breakfast'),
    ('Thalipeeth', 400, 10, 'maharashtra', 'high', 'quick', 'veg', 'breakfast'),
    ('Pithla Bhakri', 420, 15, 'maharashtra', 'low', 'medium', 'veg', 'dinner'),
    ('Zunka Bhakri', 420, 15, 'maharashtra', 'low', 'medium', 'veg', 'dinner'),
    ('Bharli Vangi + Bhakri', 420, 15, 'maharashtra', 'low', 'medium', 'veg', 'dinner'),
    ('Varan Bhaat', 420, 15, 'maharashtra', 'low', 'medium', 'veg', 'lunch'),
    ('Masale Bhaat', 420, 15, 'maharashtra', 'low', 'medium', 'veg', 'lunch'),
    ('Kothimbir Vadi', 420, 15, 'maharashtra', 'low', 'medium', 'veg', 'dinner'),
    ('Batata Vada', 240, 9, 'maharashtra', 'low', 'quick', 'veg', 'snack'),
    ('Ragda Pattice', 240, 9, 'maharashtra', 'low', 'quick', 'veg', 'snack'),
    ('Matki Usal', 420, 15, 'maharashtra', 'low', 'medium', 'veg', 'dinner'),
    ('Kolhapuri Misal', 320, 10, 'maharashtra', 'low', 'quick', 'veg', 'breakfast'),
    ('Puran Poli', 420, 15, 'maharashtra', 'low', 'medium', 'veg', 'dinner'),
    ('Shrikhand Puri', 260, 6, 'maharashtra', 'medium', 'medium', 'veg', 'dessert'),
    ('Modak', 260, 6, 'maharashtra', 'medium', 'medium', 'veg', 'dessert'),
    ('Solkadhi', 420, 15, 'maharashtra', 'low', 'medium', 'veg', 'dinner'),
    ('Bombay Sandwich', 240, 9, 'maharashtra', 'low', 'quick', 'veg', 'snack'),
    ('Egg Bhurji Pav', 360, 30, 'maharashtra', 'medium', 'medium', 'nonveg', 'breakfast'),
    ('Chicken Kolhapuri + Bhakri', 520, 36, 'maharashtra', 'medium', 'medium', 'nonveg', 'dinner'),
    ('Malvani Fish Curry + Rice', 520, 36, 'maharashtra', 'medium', 'medium', 'nonveg', 'lunch'),
    ('Kombdi Vade', 360, 30, 'maharashtra', 'medium', 'medium', 'nonveg', 'dinner'),
    ('Mutton Rassa + Bhakri', 520, 36, 'maharashtra', 'high', 'long', 'nonveg', 'dinner'),
    ('Thepla', 320, 10, 'gujarat', 'low', 'quick', 'veg', 'breakfast'),
    ('Methi Thepla + Curd', 320, 10, 'gujarat', 'low', 'quick', 'veg', 'breakfast'),
    ('Dhokla', 240, 9, 'gujarat', 'low', 'quick', 'veg', 'snack'),
    ('Khandvi', 240, 9, 'gujarat', 'low', 'quick', 'veg', 'snack'),
    ('Handvo', 420, 15, 'gujarat', 'low', 'medium', 'veg', 'dinner'),
    ('Fafda', 240, 9, 'gujarat', 'low', 'quick', 'veg', 'snack'),
    ('Fafda Jalebi', 260, 6, 'gujarat', 'medium', 'medium', 'veg', 'dessert'),
    ('Gujarati Dal + Rice', 420, 23, 'gujarat', 'low', 'medium', 'veg', 'lunch'),
    ('Undhiyu + Roti', 420, 15, 'gujarat', 'low', 'medium', 'veg', 'dinner'),
    ('Sev Tameta + Roti', 420, 15, 'gujarat', 'low', 'medium', 'veg', 'dinner'),
    ('Ringan Bateta + Roti', 420, 15, 'gujarat', 'low', 'medium', 'veg', 'dinner'),
    ('Bajra Rotla + Jaggery', 420, 15, 'gujarat', 'low', 'medium', 'veg', 'dinner'),
    ('Khichu', 420, 15, 'gujarat', 'low', 'medium', 'veg', 'dinner'),
    ('Dabeli', 240, 9, 'gujarat', 'low', 'quick', 'veg', 'snack'),
    ('Patra', 420, 15, 'gujarat', 'low', 'medium', 'veg', 'dinner'),
    ('Locho', 420, 15, 'gujarat', 'low', 'medium', 'veg', 'dinner'),
    ('Dal Dhokli', 420, 23, 'gujarat', 'low', 'medium', 'veg', 'dinner'),
    ('Gujarati Kadhi + Khichdi', 420, 15, 'gujarat', 'low', 'medium', 'veg', 'dinner'),
    ('Khaman', 420, 15, 'gujarat', 'low', 'medium', 'veg', 'dinner'),
    ('Mohanthal', 260, 6, 'gujarat', 'medium', 'medium', 'veg', 'dessert'),
    ('Basundi', 260, 6, 'gujarat', 'medium', 'medium', 'veg', 'dessert'),
    ('Dal Baati Churma', 420, 23, 'rajasthan', 'low', 'medium', 'veg', 'dinner'),
    ('Gatte Ki Sabzi + Roti', 420, 15, 'rajasthan', 'low', 'medium', 'veg', 'dinner'),
    ('Ker Sangri + Bajra Roti', 420, 15, 'rajasthan', 'low', 'medium', 'veg', 'dinner'),
    ('Bajra Khichdi', 420, 15, 'rajasthan', 'low', 'medium', 'veg', 'dinner'),
    ('Rajasthani Kadhi + Rice', 420, 15, 'rajasthan', 'low', 'medium', 'veg', 'lunch'),
    ('Papad Ki Sabzi + Roti', 420, 15, 'rajasthan', 'low', 'medium', 'veg', 'dinner'),
    ('Pyaaz Kachori', 240, 9, 'rajasthan', 'low', 'quick', 'veg', 'snack'),
    ('Mirchi Vada', 240, 9, 'rajasthan', 'low', 'quick', 'veg', 'snack'),
    ('Mawa Kachori', 240, 9, 'rajasthan', 'low', 'quick', 'veg', 'snack'),
    ('Besan Gatta Pulao', 420, 15, 'rajasthan', 'low', 'medium', 'veg', 'dinner'),
    ('Rabodi Sabzi + Roti', 420, 15, 'rajasthan', 'low', 'medium', 'veg', 'dinner'),
    ('Laal Maas + Bajra Roti', 520, 36, 'rajasthan', 'high', 'long', 'nonveg', 'dinner'),
    ('Junglee Maas', 360, 30, 'rajasthan', 'high', 'long', 'nonveg', 'dinner'),
    ('Safed Maas', 360, 30, 'rajasthan', 'high', 'long', 'nonveg', 'dinner'),
    ('Ghevar', 260, 6, 'rajasthan', 'medium', 'medium', 'veg', 'dessert'),
    ('Malpua', 260, 6, 'rajasthan', 'medium', 'medium', 'veg', 'dessert'),
    ('Bajra Roti + Garlic Chutney', 240, 9, 'rajasthan', 'low', 'quick', 'veg', 'snack'),
    ('Litti Chokha', 420, 15, 'bihar', 'low', 'medium', 'veg', 'dinner'),
    ('Sattu Sharbat', 420, 23, 'bihar', 'low', 'medium', 'veg', 'dinner'),
    ('Ghugni', 420, 15, 'bihar', 'low', 'medium', 'veg', 'dinner'),
    ('Dal Pitha', 420, 23, 'bihar', 'low', 'medium', 'veg', 'dinner'),
    ('Chana Ghugni + Roti', 420, 23, 'bihar', 'low', 'medium', 'veg', 'dinner'),
    ('Bihari Khichdi', 420, 15, 'bihar', 'low', 'medium', 'veg', 'dinner'),
    ('Aloo Chokha + Roti', 420, 15, 'bihar', 'low', 'medium', 'veg', 'dinner'),
    ('Baingan Chokha + Roti', 420, 15, 'bihar', 'low', 'medium', 'veg', 'dinner'),
    ('Thekua', 260, 6, 'bihar', 'medium', 'medium', 'veg', 'dessert'),
    ('Kadhi Bari + Rice', 420, 15, 'bihar', 'low', 'medium', 'veg', 'lunch'),
    ('Bihari Mutton Curry + Rice', 520, 36, 'bihar', 'high', 'long', 'nonveg', 'lunch'),
    ('Fish Curry + Rice Bihari', 520, 36, 'bihar', 'medium', 'medium', 'nonveg', 'lunch'),
    ('Egg Curry + Paratha', 360, 30, 'bihar', 'medium', 'medium', 'nonveg', 'breakfast'),
    ('Chura Dahi Gur', 320, 10, 'bihar', 'low', 'quick', 'veg', 'breakfast'),
    ('Khichuri', 420, 15, 'bengal', 'low', 'medium', 'veg', 'dinner'),
    ('Aloo Posto + Rice', 420, 15, 'bengal', 'low', 'medium', 'veg', 'lunch'),
    ('Shukto', 420, 15, 'bengal', 'low', 'medium', 'veg', 'dinner'),
    ('Luchi + Aloo Dum', 420, 15, 'bengal', 'low', 'medium', 'veg', 'dinner'),
    ('Cholar Dal + Luchi', 420, 23, 'bengal', 'low', 'medium', 'veg', 'dinner'),
    ('Begun Bhaja + Rice', 420, 15, 'bengal', 'low', 'medium', 'veg', 'lunch'),
    ('Mochar Ghonto + Rice', 420, 15, 'bengal', 'low', 'medium', 'veg', 'lunch'),
    ('Dhokar Dalna + Rice', 420, 23, 'bengal', 'low', 'medium', 'veg', 'lunch'),
    ('Macher Jhol + Rice', 420, 15, 'bengal', 'low', 'medium', 'veg', 'lunch'),
    ('Shorshe Ilish + Rice', 520, 36, 'bengal', 'high', 'long', 'nonveg', 'lunch'),
    ('Chingri Malai Curry + Rice', 520, 36, 'bengal', 'medium', 'medium', 'nonveg', 'lunch'),
    ('Kosha Mangsho + Rice', 420, 15, 'bengal', 'low', 'medium', 'veg', 'lunch'),
    ('Egg Devil', 360, 30, 'bengal', 'medium', 'medium', 'nonveg', 'snack'),
    ('Fish Cutlet', 360, 30, 'bengal', 'medium', 'medium', 'nonveg', 'snack'),
    ('Mughlai Paratha', 320, 10, 'bengal', 'low', 'quick', 'veg', 'breakfast'),
    ('Mishti Doi', 260, 6, 'bengal', 'medium', 'medium', 'veg', 'dessert'),
    ('Rasgulla', 260, 6, 'bengal', 'medium', 'medium', 'veg', 'dessert'),
    ('Sandesh', 260, 6, 'bengal', 'medium', 'medium', 'veg', 'dessert'),
    ('Cham Cham', 260, 6, 'bengal', 'medium', 'medium', 'veg', 'dessert'),
    ('Patishapta', 260, 6, 'bengal', 'medium', 'medium', 'veg', 'dessert'),
    ('Pakhala Bhata', 420, 15, 'odisha', 'low', 'medium', 'veg', 'dinner'),
    ('Dalma + Rice', 420, 23, 'odisha', 'low', 'medium', 'veg', 'lunch'),
    ('Santula + Roti', 420, 15, 'odisha', 'low', 'medium', 'veg', 'dinner'),
    ('Chhena Poda', 260, 6, 'odisha', 'medium', 'medium', 'veg', 'dessert'),
    ('Enduri Pitha', 420, 15, 'odisha', 'low', 'medium', 'veg', 'dinner'),
    ('Chakuli Pitha', 420, 15, 'odisha', 'low', 'medium', 'veg', 'dinner'),
    ('Dahi Bara Aloo Dum', 420, 15, 'odisha', 'low', 'medium', 'veg', 'dinner'),
    ('Ghuguni', 420, 15, 'odisha', 'low', 'medium', 'veg', 'dinner'),
    ('Machha Besara + Rice', 520, 36, 'odisha', 'medium', 'medium', 'nonveg', 'lunch'),
    ('Chingudi Jhola + Rice', 420, 15, 'odisha', 'low', 'medium', 'veg', 'lunch'),
    ('Mutton Curry Odia + Rice', 520, 36, 'odisha', 'high', 'long', 'nonveg', 'lunch'),
    ('Khechudi', 420, 15, 'odisha', 'low', 'medium', 'veg', 'dinner'),
    ('Kanika Rice', 420, 15, 'odisha', 'low', 'medium', 'veg', 'lunch'),
    ('Assamese Thali Veg', 500, 15, 'assam', 'high', 'medium', 'veg', 'lunch'),
    ('Khar + Rice', 420, 15, 'assam', 'low', 'medium', 'veg', 'lunch'),
    ('Masor Tenga + Rice', 520, 36, 'assam', 'medium', 'medium', 'nonveg', 'lunch'),
    ('Aloo Pitika + Rice', 420, 15, 'assam', 'low', 'medium', 'veg', 'lunch'),
    ('Duck Curry + Rice', 520, 36, 'assam', 'medium', 'medium', 'nonveg', 'lunch'),
    ('Pitha', 420, 15, 'assam', 'low', 'medium', 'veg', 'dinner'),
    ('Chira Doi Gur', 420, 15, 'assam', 'low', 'medium', 'veg', 'dinner'),
    ('Black Rice Pudding', 260, 6, 'assam', 'medium', 'medium', 'veg', 'dessert'),
    ('Bamboo Shoot Pork', 360, 30, 'assam', 'medium', 'medium', 'nonveg', 'dinner'),
    ('Xaak Bhaji + Rice', 420, 15, 'assam', 'low', 'medium', 'veg', 'lunch'),
    ('Chicken With Bamboo Shoot + Rice', 520, 36, 'assam', 'medium', 'medium', 'nonveg', 'lunch'),
    ('Veg Momos', 240, 9, 'northeast', 'low', 'quick', 'veg', 'snack'),
    ('Chicken Momos', 360, 30, 'northeast', 'medium', 'medium', 'nonveg', 'snack'),
    ('Thukpa Veg', 420, 15, 'northeast', 'low', 'medium', 'veg', 'dinner'),
    ('Thukpa Chicken', 360, 30, 'northeast', 'medium', 'medium', 'nonveg', 'dinner'),
    ('Chowmein Veg', 420, 15, 'northeast', 'low', 'medium', 'veg', 'dinner'),
    ('Chowmein Chicken', 360, 30, 'northeast', 'medium', 'medium', 'nonveg', 'dinner'),
    ('Ema Datshi + Rice', 420, 15, 'northeast', 'low', 'medium', 'veg', 'lunch'),
    ('Jadoh', 420, 15, 'northeast', 'low', 'medium', 'veg', 'dinner'),
    ('Dohneiiong', 420, 15, 'northeast', 'low', 'medium', 'veg', 'dinner'),
    ('Smoked Pork + Rice', 520, 36, 'northeast', 'medium', 'medium', 'nonveg', 'lunch'),
    ('Bamboo Shoot Curry + Rice', 420, 15, 'northeast', 'low', 'medium', 'veg', 'lunch'),
    ('Axone Pork + Rice', 520, 36, 'northeast', 'medium', 'medium', 'nonveg', 'lunch'),
    ('Tungrymbai + Rice', 420, 15, 'northeast', 'low', 'medium', 'veg', 'lunch'),
    ('Sel Roti', 420, 15, 'northeast', 'low', 'medium', 'veg', 'dinner'),
    ('Aloo Dum Nepali Style', 420, 15, 'northeast', 'low', 'medium', 'veg', 'dinner'),
    ('Kinema Curry + Rice', 420, 15, 'northeast', 'low', 'medium', 'veg', 'lunch'),
    ('Gyathuk', 420, 15, 'northeast', 'low', 'medium', 'veg', 'dinner'),
    ('Phagshapa', 420, 15, 'northeast', 'low', 'medium', 'veg', 'dinner'),
    ('Chhurpi Soup', 420, 15, 'northeast', 'low', 'medium', 'veg', 'dinner'),
    ('Siddu', 420, 15, 'himachal', 'low', 'medium', 'veg', 'dinner'),
    ('Madra', 420, 15, 'himachal', 'low', 'medium', 'veg', 'dinner'),
    ('Babru', 420, 15, 'himachal', 'low', 'medium', 'veg', 'dinner'),
    ('Aktori', 420, 15, 'himachal', 'low', 'medium', 'veg', 'dinner'),
    ('Dham Thali', 500, 15, 'himachal', 'high', 'medium', 'veg', 'lunch'),
    ('Tudkiya Bhath', 420, 15, 'himachal', 'low', 'medium', 'veg', 'dinner'),
    ('Chana Madra + Rice', 420, 23, 'himachal', 'low', 'medium', 'veg', 'lunch'),
    ('Sepu Vadi + Rice', 420, 15, 'himachal', 'low', 'medium', 'veg', 'lunch'),
    ('Patande', 320, 10, 'himachal', 'low', 'quick', 'veg', 'breakfast'),
    ('Bhey + Roti', 420, 15, 'himachal', 'low', 'medium', 'veg', 'dinner'),
    ('Kullu Trout + Rice', 520, 36, 'himachal', 'high', 'long', 'nonveg', 'lunch'),
    ('Chha Gosht + Rice', 520, 36, 'himachal', 'high', 'long', 'nonveg', 'lunch'),
    ('Himachali Mutton Curry', 360, 30, 'himachal', 'high', 'long', 'nonveg', 'dinner'),
    ('Mittha Rice', 420, 15, 'himachal', 'low', 'medium', 'veg', 'lunch'),
    ('Khatta Kaddu + Roti', 420, 15, 'himachal', 'low', 'medium', 'veg', 'dinner'),
    ('Red Rice + Rajma', 420, 23, 'himachal', 'low', 'medium', 'veg', 'lunch'),
    ('Buckwheat Roti + Curd', 420, 15, 'himachal', 'low', 'medium', 'veg', 'dinner'),
    ('Kashmiri Dum Aloo + Rice', 420, 15, 'kashmir', 'low', 'medium', 'veg', 'lunch'),
    ('Nadru Yakhni + Rice', 420, 15, 'kashmir', 'low', 'medium', 'veg', 'lunch'),
    ('Haak Saag + Rice', 420, 15, 'kashmir', 'low', 'medium', 'veg', 'lunch'),
    ('Kashmiri Pulao', 420, 15, 'kashmir', 'low', 'medium', 'veg', 'dinner'),
    ('Rogan Josh + Rice', 420, 15, 'kashmir', 'low', 'medium', 'veg', 'lunch'),
    ('Yakhni + Rice', 420, 15, 'kashmir', 'low', 'medium', 'veg', 'lunch'),
    ('Gushtaba + Rice', 420, 15, 'kashmir', 'low', 'medium', 'veg', 'lunch'),
    ('Rista + Rice', 420, 15, 'kashmir', 'low', 'medium', 'veg', 'lunch'),
    ('Tabak Maaz', 420, 15, 'kashmir', 'low', 'medium', 'veg', 'dinner'),
    ('Modur Pulao', 420, 15, 'kashmir', 'low', 'medium', 'veg', 'dinner'),
    ('Sheer Chai + Kulcha', 320, 10, 'kashmir', 'low', 'quick', 'veg', 'breakfast'),
    ('Kahwa + Dry Fruits', 420, 15, 'kashmir', 'low', 'medium', 'veg', 'dinner'),
    ('Kashmiri Rajma + Rice', 420, 23, 'kashmir', 'low', 'medium', 'veg', 'lunch'),
    ('Goan Fish Curry + Rice', 520, 36, 'goa', 'medium', 'medium', 'nonveg', 'lunch'),
    ('Prawn Balchao + Rice', 520, 36, 'goa', 'high', 'long', 'nonveg', 'lunch'),
    ('Chicken Xacuti + Rice', 520, 36, 'goa', 'medium', 'medium', 'nonveg', 'lunch'),
    ('Veg Xacuti + Rice', 420, 15, 'goa', 'low', 'medium', 'veg', 'lunch'),
    ('Sorak Curry + Rice', 420, 15, 'goa', 'low', 'medium', 'veg', 'lunch'),
    ('Poi Bread + Omelette', 320, 10, 'goa', 'low', 'quick', 'veg', 'breakfast'),
    ('Bebinca', 260, 6, 'goa', 'medium', 'medium', 'veg', 'dessert'),
    ('Sannas + Curry', 420, 15, 'goa', 'low', 'medium', 'veg', 'dinner'),
    ('Fish Recheado', 360, 30, 'goa', 'medium', 'medium', 'nonveg', 'dinner'),
    ('Mushroom Xacuti + Rice', 420, 15, 'goa', 'low', 'medium', 'veg', 'lunch'),
    ('Goan Pulao', 420, 15, 'goa', 'low', 'medium', 'veg', 'dinner'),
    ('Sol Kadhi Rice', 420, 15, 'goa', 'low', 'medium', 'veg', 'lunch'),
    ('Indori Poha', 320, 10, 'central', 'low', 'quick', 'veg', 'breakfast'),
    ('Jalebi Poha', 260, 6, 'central', 'medium', 'medium', 'veg', 'dessert'),
    ('Bhutte Ka Kees', 420, 15, 'central', 'low', 'medium', 'veg', 'dinner'),
    ('Dal Bafla', 420, 23, 'central', 'low', 'medium', 'veg', 'dinner'),
    ('Bhopali Gosht Korma', 360, 30, 'central', 'high', 'long', 'nonveg', 'dinner'),
    ('Sabudana Vada', 240, 9, 'central', 'low', 'quick', 'veg', 'snack'),
    ('Mawa Bati', 420, 15, 'central', 'low', 'medium', 'veg', 'dinner'),
    ('Bhopali Chicken Biryani', 520, 36, 'central', 'medium', 'medium', 'nonveg', 'lunch'),
    ('Sev Tamatar + Roti', 420, 15, 'central', 'low', 'medium', 'veg', 'dinner'),
    ('Kadhi Fafda', 240, 9, 'central', 'low', 'quick', 'veg', 'snack'),
    ('Palak Puri', 420, 15, 'central', 'low', 'medium', 'veg', 'dinner'),
    ('Malpua MP Style', 260, 6, 'central', 'medium', 'medium', 'veg', 'dessert'),
    ('Roti + Dal', 420, 23, 'all', 'low', 'medium', 'veg', 'dinner'),
    ('Roti + Sabzi', 420, 15, 'all', 'low', 'medium', 'veg', 'dinner'),
    ('Rice + Dal', 420, 23, 'all', 'low', 'medium', 'veg', 'lunch'),
    ('Khichdi', 420, 15, 'all', 'low', 'medium', 'veg', 'dinner'),
    ('Vegetable Khichdi', 420, 15, 'all', 'low', 'medium', 'veg', 'dinner'),
    ('Moong Dal Khichdi', 420, 23, 'all', 'low', 'medium', 'veg', 'dinner'),
    ('Masala Oats', 320, 10, 'all', 'low', 'quick', 'veg', 'breakfast'),
    ('Vegetable Oats', 320, 10, 'all', 'low', 'quick', 'veg', 'breakfast'),
    ('Daliya', 320, 18, 'all', 'low', 'quick', 'veg', 'breakfast'),
    ('Vegetable Daliya', 320, 18, 'all', 'low', 'quick', 'veg', 'breakfast'),
    ('Lemon Poha', 320, 10, 'all', 'low', 'quick', 'veg', 'breakfast'),
    ('Sprouts Chaat', 240, 17, 'all', 'low', 'quick', 'veg', 'snack'),
    ('Peanut Chaat', 240, 9, 'all', 'low', 'quick', 'veg', 'snack'),
    ('Tofu Salad', 240, 17, 'all', 'low', 'quick', 'veg', 'snack'),
    ('Egg Salad', 360, 30, 'all', 'medium', 'medium', 'nonveg', 'snack'),
    ('Chicken Salad', 360, 30, 'all', 'medium', 'medium', 'nonveg', 'snack'),
    ('Grilled Paneer Bowl', 420, 23, 'all', 'low', 'medium', 'veg', 'dinner'),
    ('Grilled Chicken Bowl', 360, 30, 'all', 'medium', 'medium', 'nonveg', 'dinner'),
    ('Whey Banana Shake', 240, 9, 'all', 'low', 'quick', 'veg', 'snack'),
    ('Plant Protein Shake', 240, 17, 'all', 'low', 'quick', 'veg', 'snack'),
    ('Greek Yogurt Nuts', 420, 23, 'all', 'low', 'medium', 'veg', 'dinner'),
    ('Fruit Chaat', 240, 9, 'all', 'low', 'quick', 'veg', 'snack'),
    ('Apple Peanut Butter', 500, 15, 'all', 'high', 'medium', 'veg', 'dinner'),
    ('Banana Peanut Butter', 500, 15, 'all', 'high', 'medium', 'veg', 'dinner'),
    ('Boiled Chana', 420, 23, 'all', 'low', 'medium', 'veg', 'dinner'),
    ('Boiled Rajma Salad', 240, 17, 'all', 'low', 'quick', 'veg', 'snack'),
    ('Boiled Egg Chaat', 360, 30, 'all', 'medium', 'medium', 'nonveg', 'snack'),
    ('Peanut Poha', 320, 10, 'all', 'low', 'quick', 'veg', 'breakfast'),
    ('Roti Roll Veg', 240, 9, 'all', 'low', 'quick', 'veg', 'snack'),
    ('Roti Roll Egg', 520, 36, 'all', 'medium', 'medium', 'nonveg', 'snack'),
    ('Roti Roll Chicken', 520, 36, 'all', 'medium', 'medium', 'nonveg', 'snack'),
    ('Paneer Wrap', 240, 17, 'all', 'low', 'quick', 'veg', 'snack'),
    ('Chicken Wrap', 360, 30, 'all', 'medium', 'medium', 'nonveg', 'snack'),
    ('Veg Sandwich', 240, 9, 'all', 'low', 'quick', 'veg', 'snack'),
    ('Egg Sandwich', 360, 30, 'all', 'medium', 'medium', 'nonveg', 'snack'),
    ('Chicken Sandwich', 360, 30, 'all', 'medium', 'medium', 'nonveg', 'snack'),
    ('Kheer', 260, 6, 'all', 'medium', 'medium', 'veg', 'dessert'),
    ('Rice Kheer', 260, 6, 'all', 'medium', 'medium', 'veg', 'dessert'),
    ('Vermicelli Kheer', 260, 6, 'all', 'medium', 'medium', 'veg', 'dessert'),
    ('Gajar Halwa', 260, 6, 'all', 'medium', 'medium', 'veg', 'dessert'),
    ('Suji Halwa', 260, 6, 'all', 'medium', 'medium', 'veg', 'dessert'),
    ('Besan Ladoo', 260, 6, 'all', 'medium', 'medium', 'veg', 'dessert'),
    ('Til Ladoo', 260, 6, 'all', 'medium', 'medium', 'veg', 'dessert'),
    ('Peanut Ladoo', 260, 6, 'all', 'medium', 'medium', 'veg', 'dessert'),
    ('Coconut Ladoo', 260, 6, 'all', 'medium', 'medium', 'veg', 'dessert'),
    ('Ragi Malt', 420, 15, 'all', 'low', 'medium', 'veg', 'dinner'),
    ('Millet Khichdi', 420, 15, 'all', 'low', 'medium', 'veg', 'dinner'),
    ('Jowar Roti + Sabzi', 420, 15, 'all', 'low', 'medium', 'veg', 'dinner'),
    ('Bajra Roti + Dal', 420, 23, 'all', 'low', 'medium', 'veg', 'dinner'),
    ('Ragi Dosa', 320, 10, 'all', 'low', 'quick', 'veg', 'breakfast'),
    ('Oats Idli', 320, 10, 'all', 'low', 'quick', 'veg', 'breakfast'),
    ('Aloo Gobi + Rice', 420, 11, 'north', 'low', 'quick', 'veg', 'lunch'),
    ('Aloo Gobi + Jeera Rice', 460, 12, 'north', 'medium', 'quick', 'veg', 'lunch'),
    ('Aloo Gobi + Paratha', 480, 13, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Aloo Gobi + Naan', 500, 14, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Aloo Gobi + Bajra Roti', 440, 13, 'north', 'medium', 'quick', 'veg', 'dinner'),
    ('Aloo Gobi + Jowar Roti', 430, 13, 'north', 'medium', 'quick', 'veg', 'dinner'),
    ('Aloo Gobi + Bhakri', 450, 13, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Aloo Gobi + Millet Rice', 430, 12, 'north', 'medium', 'quick', 'veg', 'lunch'),
    ('Bhindi Masala + Rice', 420, 11, 'north', 'low', 'quick', 'veg', 'lunch'),
    ('Bhindi Masala + Jeera Rice', 460, 12, 'north', 'medium', 'quick', 'veg', 'lunch'),
    ('Bhindi Masala + Paratha', 480, 13, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Bhindi Masala + Naan', 500, 14, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Bhindi Masala + Bajra Roti', 440, 13, 'north', 'medium', 'quick', 'veg', 'dinner'),
    ('Bhindi Masala + Jowar Roti', 430, 13, 'north', 'medium', 'quick', 'veg', 'dinner'),
    ('Bhindi Masala + Bhakri', 450, 13, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Bhindi Masala + Millet Rice', 430, 12, 'north', 'medium', 'quick', 'veg', 'lunch'),
    ('Baingan Bharta + Rice', 420, 11, 'north', 'low', 'quick', 'veg', 'lunch'),
    ('Baingan Bharta + Jeera Rice', 460, 12, 'north', 'medium', 'quick', 'veg', 'lunch'),
    ('Baingan Bharta + Paratha', 480, 13, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Baingan Bharta + Naan', 500, 14, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Baingan Bharta + Bajra Roti', 440, 13, 'north', 'medium', 'quick', 'veg', 'dinner'),
    ('Baingan Bharta + Jowar Roti', 430, 13, 'north', 'medium', 'quick', 'veg', 'dinner'),
    ('Baingan Bharta + Bhakri', 450, 13, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Baingan Bharta + Millet Rice', 430, 12, 'north', 'medium', 'quick', 'veg', 'lunch'),
    ('Lauki Chana Dal + Roti', 400, 21, 'north', 'low', 'quick', 'veg', 'dinner'),
    ('Lauki Chana Dal + Rice', 420, 21, 'north', 'low', 'quick', 'veg', 'lunch'),
    ('Lauki Chana Dal + Jeera Rice', 460, 22, 'north', 'medium', 'quick', 'veg', 'lunch'),
    ('Lauki Chana Dal + Paratha', 480, 23, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Lauki Chana Dal + Naan', 500, 24, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Lauki Chana Dal + Bajra Roti', 440, 23, 'north', 'medium', 'quick', 'veg', 'dinner'),
    ('Lauki Chana Dal + Jowar Roti', 430, 23, 'north', 'medium', 'quick', 'veg', 'dinner'),
    ('Lauki Chana Dal + Bhakri', 450, 23, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Lauki Chana Dal + Millet Rice', 430, 22, 'north', 'medium', 'quick', 'veg', 'lunch'),
    ('Tinda Masala + Roti', 400, 11, 'north', 'low', 'quick', 'veg', 'dinner'),
    ('Tinda Masala + Rice', 420, 11, 'north', 'low', 'quick', 'veg', 'lunch'),
    ('Tinda Masala + Jeera Rice', 460, 12, 'north', 'medium', 'quick', 'veg', 'lunch'),
    ('Tinda Masala + Paratha', 480, 13, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Tinda Masala + Naan', 500, 14, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Tinda Masala + Bajra Roti', 440, 13, 'north', 'medium', 'quick', 'veg', 'dinner'),
    ('Tinda Masala + Jowar Roti', 430, 13, 'north', 'medium', 'quick', 'veg', 'dinner'),
    ('Tinda Masala + Bhakri', 450, 13, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Tinda Masala + Millet Rice', 430, 12, 'north', 'medium', 'quick', 'veg', 'lunch'),
    ('Cabbage Peas + Roti', 400, 11, 'north', 'low', 'quick', 'veg', 'dinner'),
    ('Cabbage Peas + Rice', 420, 11, 'north', 'low', 'quick', 'veg', 'lunch'),
    ('Cabbage Peas + Jeera Rice', 460, 12, 'north', 'medium', 'quick', 'veg', 'lunch'),
    ('Cabbage Peas + Paratha', 480, 13, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Cabbage Peas + Naan', 500, 14, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Cabbage Peas + Bajra Roti', 440, 13, 'north', 'medium', 'quick', 'veg', 'dinner'),
    ('Cabbage Peas + Jowar Roti', 430, 13, 'north', 'medium', 'quick', 'veg', 'dinner'),
    ('Cabbage Peas + Bhakri', 450, 13, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Cabbage Peas + Millet Rice', 430, 12, 'north', 'medium', 'quick', 'veg', 'lunch'),
    ('Methi Aloo + Roti', 400, 11, 'north', 'low', 'quick', 'veg', 'dinner'),
    ('Methi Aloo + Rice', 420, 11, 'north', 'low', 'quick', 'veg', 'lunch'),
    ('Methi Aloo + Jeera Rice', 460, 12, 'north', 'medium', 'quick', 'veg', 'lunch'),
    ('Methi Aloo + Paratha', 480, 13, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Methi Aloo + Naan', 500, 14, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Methi Aloo + Bajra Roti', 440, 13, 'north', 'medium', 'quick', 'veg', 'dinner'),
    ('Methi Aloo + Jowar Roti', 430, 13, 'north', 'medium', 'quick', 'veg', 'dinner'),
    ('Methi Aloo + Bhakri', 450, 13, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Methi Aloo + Millet Rice', 430, 12, 'north', 'medium', 'quick', 'veg', 'lunch'),
    ('Palak Corn + Roti', 400, 11, 'north', 'low', 'quick', 'veg', 'dinner'),
    ('Palak Corn + Rice', 420, 11, 'north', 'low', 'quick', 'veg', 'lunch'),
    ('Palak Corn + Jeera Rice', 460, 12, 'north', 'medium', 'quick', 'veg', 'lunch'),
    ('Palak Corn + Paratha', 480, 13, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Palak Corn + Naan', 500, 14, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Palak Corn + Bajra Roti', 440, 13, 'north', 'medium', 'quick', 'veg', 'dinner'),
    ('Palak Corn + Jowar Roti', 430, 13, 'north', 'medium', 'quick', 'veg', 'dinner'),
    ('Palak Corn + Bhakri', 450, 13, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Palak Corn + Millet Rice', 430, 12, 'north', 'medium', 'quick', 'veg', 'lunch'),
    ('Karela Onion + Roti', 400, 11, 'north', 'low', 'quick', 'veg', 'dinner'),
    ('Karela Onion + Rice', 420, 11, 'north', 'low', 'quick', 'veg', 'lunch'),
    ('Karela Onion + Jeera Rice', 460, 12, 'north', 'medium', 'quick', 'veg', 'lunch'),
    ('Karela Onion + Paratha', 480, 13, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Karela Onion + Naan', 500, 14, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Karela Onion + Bajra Roti', 440, 13, 'north', 'medium', 'quick', 'veg', 'dinner'),
    ('Karela Onion + Jowar Roti', 430, 13, 'north', 'medium', 'quick', 'veg', 'dinner'),
    ('Karela Onion + Bhakri', 450, 13, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Karela Onion + Millet Rice', 430, 12, 'north', 'medium', 'quick', 'veg', 'lunch'),
    ('Pumpkin Sabzi + Roti', 400, 11, 'north', 'low', 'quick', 'veg', 'dinner'),
    ('Pumpkin Sabzi + Rice', 420, 11, 'north', 'low', 'quick', 'veg', 'lunch'),
    ('Pumpkin Sabzi + Jeera Rice', 460, 12, 'north', 'medium', 'quick', 'veg', 'lunch'),
    ('Pumpkin Sabzi + Paratha', 480, 13, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Pumpkin Sabzi + Naan', 500, 14, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Pumpkin Sabzi + Bajra Roti', 440, 13, 'north', 'medium', 'quick', 'veg', 'dinner'),
    ('Pumpkin Sabzi + Jowar Roti', 430, 13, 'north', 'medium', 'quick', 'veg', 'dinner'),
    ('Pumpkin Sabzi + Bhakri', 450, 13, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Pumpkin Sabzi + Millet Rice', 430, 12, 'north', 'medium', 'quick', 'veg', 'lunch'),
    ('Beans Poriyal + Roti', 400, 11, 'north', 'low', 'quick', 'veg', 'dinner'),
    ('Beans Poriyal + Rice', 420, 11, 'north', 'low', 'quick', 'veg', 'lunch'),
    ('Beans Poriyal + Jeera Rice', 460, 12, 'north', 'medium', 'quick', 'veg', 'lunch'),
    ('Beans Poriyal + Paratha', 480, 13, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Beans Poriyal + Naan', 500, 14, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Beans Poriyal + Bajra Roti', 440, 13, 'north', 'medium', 'quick', 'veg', 'dinner'),
    ('Beans Poriyal + Jowar Roti', 430, 13, 'north', 'medium', 'quick', 'veg', 'dinner'),
    ('Beans Poriyal + Bhakri', 450, 13, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Beans Poriyal + Millet Rice', 430, 12, 'north', 'medium', 'quick', 'veg', 'lunch'),
    ('Cucumber Raita + Roti', 400, 11, 'north', 'low', 'quick', 'veg', 'dinner'),
    ('Cucumber Raita + Rice', 420, 11, 'north', 'low', 'quick', 'veg', 'lunch'),
    ('Cucumber Raita + Jeera Rice', 460, 12, 'north', 'medium', 'quick', 'veg', 'lunch'),
    ('Cucumber Raita + Paratha', 480, 13, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Cucumber Raita + Naan', 500, 14, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Cucumber Raita + Bajra Roti', 440, 13, 'north', 'medium', 'quick', 'veg', 'dinner'),
    ('Cucumber Raita + Jowar Roti', 430, 13, 'north', 'medium', 'quick', 'veg', 'dinner'),
    ('Cucumber Raita + Bhakri', 450, 13, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Cucumber Raita + Millet Rice', 430, 12, 'north', 'medium', 'quick', 'veg', 'lunch'),
    ('Gajar Matar + Roti', 400, 11, 'north', 'low', 'quick', 'veg', 'dinner'),
    ('Gajar Matar + Rice', 420, 11, 'north', 'low', 'quick', 'veg', 'lunch'),
    ('Gajar Matar + Jeera Rice', 460, 12, 'north', 'medium', 'quick', 'veg', 'lunch'),
    ('Gajar Matar + Paratha', 480, 13, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Gajar Matar + Naan', 500, 14, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Gajar Matar + Bajra Roti', 440, 13, 'north', 'medium', 'quick', 'veg', 'dinner'),
    ('Gajar Matar + Jowar Roti', 430, 13, 'north', 'medium', 'quick', 'veg', 'dinner'),
    ('Gajar Matar + Bhakri', 450, 13, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Gajar Matar + Millet Rice', 430, 12, 'north', 'medium', 'quick', 'veg', 'lunch'),
    ('Soya Chaap Curry + Roti', 400, 21, 'north', 'low', 'quick', 'veg', 'dinner'),
    ('Soya Chaap Curry + Rice', 420, 21, 'north', 'low', 'quick', 'veg', 'lunch'),
    ('Soya Chaap Curry + Jeera Rice', 460, 22, 'north', 'medium', 'quick', 'veg', 'lunch'),
    ('Soya Chaap Curry + Paratha', 480, 23, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Soya Chaap Curry + Naan', 500, 24, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Soya Chaap Curry + Bajra Roti', 440, 23, 'north', 'medium', 'quick', 'veg', 'dinner'),
    ('Soya Chaap Curry + Jowar Roti', 430, 23, 'north', 'medium', 'quick', 'veg', 'dinner'),
    ('Soya Chaap Curry + Bhakri', 450, 23, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Soya Chaap Curry + Millet Rice', 430, 22, 'north', 'medium', 'quick', 'veg', 'lunch'),
    ('Mushroom Masala + Roti', 400, 11, 'north', 'low', 'quick', 'veg', 'dinner'),
    ('Mushroom Masala + Rice', 420, 11, 'north', 'low', 'quick', 'veg', 'lunch'),
    ('Mushroom Masala + Jeera Rice', 460, 12, 'north', 'medium', 'quick', 'veg', 'lunch'),
    ('Mushroom Masala + Paratha', 480, 13, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Mushroom Masala + Naan', 500, 14, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Mushroom Masala + Bajra Roti', 440, 13, 'north', 'medium', 'quick', 'veg', 'dinner'),
    ('Mushroom Masala + Jowar Roti', 430, 13, 'north', 'medium', 'quick', 'veg', 'dinner'),
    ('Mushroom Masala + Bhakri', 450, 13, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Mushroom Masala + Millet Rice', 430, 12, 'north', 'medium', 'quick', 'veg', 'lunch'),
    ('Paneer Capsicum + Roti', 400, 21, 'north', 'low', 'quick', 'veg', 'dinner'),
    ('Paneer Capsicum + Rice', 420, 21, 'north', 'low', 'quick', 'veg', 'lunch'),
    ('Paneer Capsicum + Jeera Rice', 460, 22, 'north', 'medium', 'quick', 'veg', 'lunch'),
    ('Paneer Capsicum + Paratha', 480, 23, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Paneer Capsicum + Naan', 500, 24, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Paneer Capsicum + Bajra Roti', 440, 23, 'north', 'medium', 'quick', 'veg', 'dinner'),
    ('Paneer Capsicum + Jowar Roti', 430, 23, 'north', 'medium', 'quick', 'veg', 'dinner'),
    ('Paneer Capsicum + Bhakri', 450, 23, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Paneer Capsicum + Millet Rice', 430, 22, 'north', 'medium', 'quick', 'veg', 'lunch'),
    ('Tofu Masala + Roti', 400, 21, 'north', 'low', 'quick', 'veg', 'dinner'),
    ('Tofu Masala + Rice', 420, 21, 'north', 'low', 'quick', 'veg', 'lunch'),
    ('Tofu Masala + Jeera Rice', 460, 22, 'north', 'medium', 'quick', 'veg', 'lunch'),
    ('Tofu Masala + Paratha', 480, 23, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Tofu Masala + Naan', 500, 24, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Tofu Masala + Bajra Roti', 440, 23, 'north', 'medium', 'quick', 'veg', 'dinner'),
    ('Tofu Masala + Jowar Roti', 430, 23, 'north', 'medium', 'quick', 'veg', 'dinner'),
    ('Tofu Masala + Bhakri', 450, 23, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Tofu Masala + Millet Rice', 430, 22, 'north', 'medium', 'quick', 'veg', 'lunch'),
    ('Chana Masala + Roti', 400, 21, 'north', 'low', 'quick', 'veg', 'dinner'),
    ('Chana Masala + Rice', 420, 21, 'north', 'low', 'quick', 'veg', 'lunch'),
    ('Chana Masala + Jeera Rice', 460, 22, 'north', 'medium', 'quick', 'veg', 'lunch'),
    ('Chana Masala + Paratha', 480, 23, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Chana Masala + Naan', 500, 24, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Chana Masala + Bajra Roti', 440, 23, 'north', 'medium', 'quick', 'veg', 'dinner'),
    ('Chana Masala + Jowar Roti', 430, 23, 'north', 'medium', 'quick', 'veg', 'dinner'),
    ('Chana Masala + Bhakri', 450, 23, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Chana Masala + Millet Rice', 430, 22, 'north', 'medium', 'quick', 'veg', 'lunch'),
    ('Rajma Masala + Roti', 400, 21, 'north', 'low', 'quick', 'veg', 'dinner'),
    ('Rajma Masala + Jeera Rice', 460, 22, 'north', 'medium', 'quick', 'veg', 'lunch'),
    ('Rajma Masala + Paratha', 480, 23, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Rajma Masala + Naan', 500, 24, 'north', 'medium', 'medium', 'veg', 'dinner'),
    ('Rajma Masala + Bajra Roti', 440, 23, 'north', 'medium', 'quick', 'veg', 'dinner'),
    ('Rajma Masala + Jowar Roti', 430, 23, 'north', 'medium', 'quick', 'veg', 'dinner'),
    ('Chicken Curry + Jeera Rice', 570, 37, 'north', 'medium', 'medium', 'nonveg', 'lunch'),
    ('Chicken Curry + Paratha', 590, 38, 'north', 'medium', 'medium', 'nonveg', 'dinner'),
    ('Chicken Curry + Naan', 610, 39, 'north', 'medium', 'medium', 'nonveg', 'dinner'),
    ('Chicken Curry + Bajra Roti', 550, 38, 'north', 'medium', 'medium', 'nonveg', 'dinner'),
    ('Egg Curry + Rice', 460, 26, 'north', 'medium', 'medium', 'nonveg', 'lunch'),
    ('Egg Curry + Jeera Rice', 500, 27, 'north', 'medium', 'medium', 'nonveg', 'lunch'),
    ('Egg Curry + Naan', 540, 29, 'north', 'medium', 'medium', 'nonveg', 'dinner'),
    ('Egg Curry + Bajra Roti', 480, 28, 'north', 'medium', 'medium', 'nonveg', 'dinner'),
    ('Fish Curry + Roti', 480, 34, 'north', 'medium', 'medium', 'nonveg', 'dinner'),
    ('Fish Curry + Jeera Rice', 540, 35, 'north', 'medium', 'medium', 'nonveg', 'lunch'),
    ('Fish Curry + Paratha', 560, 36, 'north', 'medium', 'medium', 'nonveg', 'dinner'),
    ('Fish Curry + Naan', 580, 37, 'north', 'medium', 'medium', 'nonveg', 'dinner'),
    ('Fish Curry + Bajra Roti', 520, 36, 'north', 'medium', 'medium', 'nonveg', 'dinner'),
    ('Chicken Keema + Roti', 520, 38, 'north', 'medium', 'medium', 'nonveg', 'dinner'),
    ('Chicken Keema + Rice', 540, 38, 'north', 'medium', 'medium', 'nonveg', 'lunch'),
    ('Chicken Keema + Jeera Rice', 580, 39, 'north', 'medium', 'medium', 'nonveg', 'lunch'),
    ('Chicken Keema + Paratha', 600, 40, 'north', 'medium', 'medium', 'nonveg', 'dinner'),
    ('Chicken Keema + Naan', 620, 41, 'north', 'medium', 'medium', 'nonveg', 'dinner'),
    ('Chicken Keema + Bajra Roti', 560, 40, 'north', 'medium', 'medium', 'nonveg', 'dinner'),
    ('Mutton Curry + Rice', 620, 40, 'north', 'high', 'long', 'nonveg', 'lunch'),
    ('Mutton Curry + Jeera Rice', 660, 41, 'north', 'high', 'long', 'nonveg', 'lunch'),
    ('Mutton Curry + Paratha', 680, 42, 'north', 'high', 'long', 'nonveg', 'dinner'),
    ('Mutton Curry + Bajra Roti', 640, 42, 'north', 'high', 'long', 'nonveg', 'dinner'),
    ('Chicken Tikka Masala + Roti', 560, 40, 'north', 'medium', 'medium', 'nonveg', 'dinner'),
    ('Chicken Tikka Masala + Rice', 580, 40, 'north', 'medium', 'medium', 'nonveg', 'lunch'),
    ('Chicken Tikka Masala + Jeera Rice', 620, 41, 'north', 'medium', 'medium', 'nonveg', 'lunch'),
    ('Chicken Tikka Masala + Paratha', 640, 42, 'north', 'medium', 'medium', 'nonveg', 'dinner'),
    ('Chicken Tikka Masala + Naan', 660, 43, 'north', 'medium', 'medium', 'nonveg', 'dinner'),
    ('Chicken Tikka Masala + Bajra Roti', 600, 42, 'north', 'medium', 'medium', 'nonveg', 'dinner'),
    ('Fish Masala + Roti', 510, 36, 'north', 'medium', 'medium', 'nonveg', 'dinner'),
    ('Fish Masala + Rice', 530, 36, 'north', 'medium', 'medium', 'nonveg', 'lunch'),
    ('Fish Masala + Jeera Rice', 570, 37, 'north', 'medium', 'medium', 'nonveg', 'lunch'),
    ('Fish Masala + Paratha', 590, 38, 'north', 'medium', 'medium', 'nonveg', 'dinner'),
    ('Fish Masala + Naan', 610, 39, 'north', 'medium', 'medium', 'nonveg', 'dinner'),
    ('Fish Masala + Bajra Roti', 550, 38, 'north', 'medium', 'medium', 'nonveg', 'dinner'),
    ('Egg Bhurji + Roti', 420, 22, 'north', 'medium', 'medium', 'nonveg', 'dinner'),
    ('Egg Bhurji + Rice', 440, 22, 'north', 'medium', 'medium', 'nonveg', 'lunch'),
    ('Egg Bhurji + Jeera Rice', 480, 23, 'north', 'medium', 'medium', 'nonveg', 'lunch'),
    ('Egg Bhurji + Paratha', 500, 24, 'north', 'medium', 'medium', 'nonveg', 'dinner'),
    ('Egg Bhurji + Naan', 520, 25, 'north', 'medium', 'medium', 'nonveg', 'dinner'),
    ('Egg Bhurji + Bajra Roti', 460, 24, 'north', 'medium', 'medium', 'nonveg', 'dinner'),
]
